# See https://hub.docker.com/r/bitnami/kafka/tags for the complete list.
version: '3'
services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: bitnami/zookeeper:latest
    ports:
    - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    # If you are on arm64 and experiencing issues with the tests (hangs,
    # connection reset) then try the following in order:

    # - stopping and removing all downloaded container images
    # - ensuring you have the latest Docker Desktop version
    # - factory reset your Docker Desktop settings

    # If you are still running into issues please post in #help-infra-seg.
    platform: linux/amd64
  kafka:
    container_name: kafka
    image: bitnami/kafka:2.3.1-ol-7-r61
    restart: on-failure:3
    links:
    - zookeeper
    ports:
    - 9092:9092
    - 9093:9093
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CFG_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_CFG_ADVERTISED_PORT: '9092'
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_MESSAGE_MAX_BYTES: '200000000'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:9092,SASL_PLAINTEXT://:9093'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,SASL_PLAINTEXT://localhost:9093'
      KAFKA_CFG_SASL_ENABLED_MECHANISMS: 'PLAIN,SCRAM-SHA-256,SCRAM-SHA-512'
      KAFKA_CFG_AUTHORIZER_CLASS_NAME: 'kafka.security.auth.SimpleAclAuthorizer'
      KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
      KAFKA_INTER_BROKER_USER: adminplain
      KAFKA_INTER_BROKER_PASSWORD: admin-secret
      KAFKA_BROKER_USER: adminplain
      KAFKA_BROKER_PASSWORD: admin-secret
      ALLOW_PLAINTEXT_LISTENER: yes
    entrypoint:
    - "/bin/bash"
    - "-c"
    - /opt/bitnami/kafka/bin/kafka-configs.sh --zookeeper zookeeper:2181 --alter --add-config
      "SCRAM-SHA-256=[password=admin-secret-256],SCRAM-SHA-512=[password=admin-secret-512]"
      --entity-type users --entity-name adminscram; exec /entrypoint.sh /run.sh
    # See platform comment above for amd64/arm64 troubleshooting
    platform: linux/amd64
